### ISSUE TITLE
Integration records timestamp at the end of the run instead of the beginning.

### ISSUE THREAD

**Issue by dwestness** [tenable/integration-jira-cloud#107]
I run the utility with the -d flag for daemon and i understand that it appends an observed_since criteria for subsequent delta runs, however it appears to be that this observed_since date is based upon the time the previous job ended instead of when the previous job started... So that means any observations that occured "during" the previous run are missed. I have been going through periodically and restarted the job to allow a full sync and it generates a ton of activity that is not caught by the daemon run

**Comment by SteveMcGrath** [comment]
1.1.22 should address this issue

**Comment by dwestness** [comment]
Updated and observed_since unix stamp is now operating as desired. Thank you

**Comment by dwestness** [comment]
I have noticed now that while the daemon ovserved_since unix timestamp is properly reflected as the start time of the previous run... Now none of my daemon/delta runs are producing any updates/creations/closures of issues that have in fact been updated. I set it to run the daemon every 1 hour and ensured there were plenty of scan jobs run which produced critical/high results, yet the daemon runs never take action upon them now

**Comment by SteveMcGrath** [comment]
yeah....this seems like a stupid mistake.  My apologies.  Fix one thing and break another.  The issue was that while I changed when the timestamps were being set, the last_ run was being set right before the next run was to occur, so it was overloading the old value before it could use it.  Rookie mistake.

The fix (and next version to be released right after) addresses this by using observed_since universally, and overloading observed_since with last_run at the end of each run.  To be honest, that loop is pretty janky and should be refactored anyway.

Currently running the test to validate as we speak.

**Comment by SteveMcGrath** [comment]
Looks like I had already pushed out 1.1.23 before updating the changelog, so it has been addressed as of 6 days ago when I started working on it ;)
