### ISSUE TITLE
Subtask uniqueness searching incorrectly specified IPv4 and IPv6 fields

### ISSUE THREAD

**Issue by dsouza713** [tenable/integration-jira-cloud#15]
looking at the debug logs of the script running and Jira. It looks like the script updates existing subtasks without creating new ones:
So if a vulnerbility has 4 IPs/assets associated with it:
10.0.0.1
10.0.0.2
10.0.0.3
10.0.0.4
I can see calls being made to Jira for each of the IP's. However it updates the same subtask, so in the end you will have the ip 10.0.0.4.

Is the script limited to creating only 1 subtasks? hence why it doesn't create new subtasks?
# This section defines the issue-types & how to search them.  There should only# ever be a singular "standard" and no more than 1 "subtask".  The issue-type# name is what will be used throughout the rest of the config file to determine# what issue-type gets what data fields.

**Comment by SteveMcGrath** [comment]
It creates a sub-task for each unique vuln instance, as noted in point 2 of the readme.  From there it will update tasks that meed the correct criteria defined in the configuration.

https://github.com/tenable/integration-jira-cloud/blob/master/tenable_jira/config.py#L111-L116

It will _always_ update the task when it comes across the same vulnerability, which is where the confusion may lie.  This is mostly to ensure that the more current and correct vulnerability definition is applied to the task.

**Comment by r1ckyb0nd** [comment]
@SteveMcGrath ,
So if a Vulnerability is on multiple assets, it will still only open one subtask?
That is not what the documentation states. https://docs.tenable.com/integrations/Atlassian/Jira/Content/Jira%20SC/welcome_sc.htm

![image](https://user-images.githubusercontent.com/10982727/75364544-e7be6580-5889-11ea-8037-d65c2888e4d4.png)

It looks like it is just updating the subtask with the next asset's information.

**Comment by SteveMcGrath** [comment]
The Jira plugin is a different integration than this Jira cloud integration.

**Comment by SteveMcGrath** [comment]
If you're seeing different behavior, then please post your configuration and the latest debug log.

**Comment by r1ckyb0nd** [comment]
good point, wrong link.
This from the description from the front page of integration-jira-cloud 
"The integration creates a Task for each Vulnerability and creates each vulnerability instance as a Sub-task. Example: if you have 5 hosts with plugin 151074, the integration creates 1 Task with the details of 151074 and creates 5 Sub-tasks, each one pointing to a specific instance of the vulnerability on a specific host."

What we are seeing is 1 Task with the details of 151074, then instead of 5 sub-tasks for each asset, we are seeing one sub-task get updated 5 times. 


[Log_showingcalls_made to jira.log](https://github.com/tenable/integration-jira-cloud/files/4256956/Log_showingcalls_made.to.jira.log)

for the configuration file, Denzyl will have to upload that.

**Comment by SteveMcGrath** [comment]
It ended up being an issue with some field name changes when in development.  Updated to 1.1.2 with the updated JQL search parameters.
