### ISSUE TITLE
Duplicate vulnerabilities are created for the same vulnerability and same IP

### ISSUE THREAD

**Issue by dsouza713** [tenable/integration-jira-cloud#16]
Hi Steve, 

It looks like another issue has arised based on the change that was made. I noticed that the system creates duplicates subtasks depending on how many times the script was run instead of updating the subtasks already created, it creates new subtask:
![image](https://user-images.githubusercontent.com/61409621/75458017-182efe00-5975-11ea-9b44-7527cae144b6.png)

In the above image you will see that the same IP has multiple issues created for the same vulnerability. Shouldn't the script be updating the current issues based on IP?

**Comment by SteveMcGrath** [comment]
Yup, when i added the Platform field to the JQL searches (as it should have always been) it surfaced an issue where the JQL constructor would always report it as EMPTY, namely because that value isn't derived from the data, but the config.

1.1.3 uploaded that should resolve the issue.  Also9thanks for your understanding and help.
