### ISSUE TITLE
Can we use this integration plugin for Jira Server (On-prem) ?

### ISSUE THREAD

**Issue by bogdanovser** [tenable/integration-jira-cloud#173]
Hi, Guys.

Sory for off top. :)
Can we use this integration  jira-cloud #plugin for Jira Server (On-prem) ?
I ask because this jira-cloud plugin more customisable in contrast to "Tenable Plug-in for Jira" in  Atlassian Marketplace.

**Comment by spatelte** [comment]
@bogdanovser for the JIRA DC or Server we have plugin which is available on Atlassian marketplace, which is [https://marketplace.atlassian.com/apps/1219681/tenable-plug-in-for-jira?tab=overview&hosting=datacenter](https://marketplace.atlassian.com/apps/1219681/tenable-plug-in-for-jira?tab=overview&hosting=datacenter)

**Comment by andytsmith** [comment]
+1 for a jira server / datacentre integration if at all possible (rather than the Atlassian marketplace version). We are unable to close tickets with the one on Atlassian marketplace when the host no longer exists and there doesn't seem to be an easy/timely way of getting the feature added. At least with this version we would have the ability to use the Vulnerability last seen field to allow us to automate something easily to close the ephemeral tickets off.
