### ISSUE TITLE
Issue during execution

### ISSUE THREAD

**Issue by ghost** [tenable/integration-jira-cloud#211]
17:10:59 Traceback (most recent call last):
17:11:00   File "C:\Program Files\Python311\Jira-Tenable\Scripts\tenable-jira-script.py", line 33, in <module>
17:11:00     sys.exit(load_entry_point('tenable-jira-cloud==1.2.3', 'console_scripts', 'tenable-jira')())
17:11:00              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
17:11:00   File "C:\Program Files\Python311\Jira-Tenable\Lib\site-packages\click\core.py", line 1130, in __call__
17:11:00     return self.main(*args, **kwargs)
17:11:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^
17:11:00   File "C:\Program Files\Python311\Jira-Tenable\Lib\site-packages\click\core.py", line 1055, in main
17:11:00     rv = self.invoke(ctx)
17:11:00          ^^^^^^^^^^^^^^^^
17:11:00   File "C:\Program Files\Python311\Jira-Tenable\Lib\site-packages\click\core.py", line 1404, in invoke
17:11:00     return ctx.invoke(self.callback, **ctx.params)
17:11:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
17:11:00   File "C:\Program Files\Python311\Jira-Tenable\Lib\site-packages\click\core.py", line 760, in invoke
17:11:00     return __callback(*args, **kwargs)
17:11:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
17:11:00   File "C:\Program Files\Python311\Jira-Tenable\Lib\site-packages\tenable_jira\cli.py", line 219, in cli
17:11:00     if config.get('service', {}).get('interval', 0) > 0:
17:11:00        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
17:11:00 TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by samryanturner** [comment]
occurs in the later part of the job, during closing of issues that have found to be fixed in Tenable.

**Comment by samryanturner** [comment]
05:31:57 ### Available IssueTypes
05:31:57 ```yaml
05:31:57 10005: Sub-task
05:31:57 10004: Task
05:31:57 ```
05:31:57 
05:32:00 /-------------------------------NOTICE-----------------------------------\
05:32:00 | The output above is helpful for us to troubleshoot exactly what is     |
05:32:00 | happening within the code and offer a diagnosis for how to correct.    |
05:32:00 | Please note that while some basic redaction has already been performed |
05:32:00 | that we ask you to review the information you're about to send and     |
05:32:00 | ensure that nothing deemed sensitive is transmitted.                   |
05:32:00 | ---------------------------------------------------------------------- |
05:32:00 | -- Copy of output saved to "issue_debug.md"                            |
05:32:00 \------------------------------------------------------------------------/
05:32:00 Traceback (most recent call last):
05:32:00   File "C:\Program Files\Python311\Jira-Tenable\Scripts\tenable-jira-script.py", line 33, in <module>
05:32:00     sys.exit(load_entry_point('tenable-jira-cloud==1.2.3', 'console_scripts', 'tenable-jira')())
05:32:00              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05:32:00   File "C:\Program Files\Python311\Jira-Tenable\Lib\site-packages\click\core.py", line 1130, in __call__
05:32:00     return self.main(*args, **kwargs)
05:32:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^
05:32:00   File "C:\Program Files\Python311\Jira-Tenable\Lib\site-packages\click\core.py", line 1055, in main
05:32:00     rv = self.invoke(ctx)
05:32:00          ^^^^^^^^^^^^^^^^
05:32:00   File "C:\Program Files\Python311\Jira-Tenable\Lib\site-packages\click\core.py", line 1404, in invoke
05:32:00     return ctx.invoke(self.callback, **ctx.params)
05:32:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05:32:00   File "C:\Program Files\Python311\Jira-Tenable\Lib\site-packages\click\core.py", line 760, in invoke
05:32:00     return __callback(*args, **kwargs)
05:32:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
05:32:00   File "C:\Program Files\Python311\Jira-Tenable\Lib\site-packages\tenable_jira\cli.py", line 207, in cli
05:32:00     os.remove('tenable_debug.log')
05:32:00 PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'tenable_debug.log'
05:32:00 Build step 'Windows Exe' marked build as failure
05:32:01 Finished: FAILURE

**Comment by samryanturner** [comment]
`22:48:17 Traceback (most recent call last):
22:48:20   File "C:\Program Files\Python311\Jira-Tenable\Scripts\tenable-jira-script.py", line 33, in <module>
22:48:20     sys.exit(load_entry_point('tenable-jira-cloud==1.2.3', 'console_scripts', 'tenable-jira')())
22:48:20              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:48:20   File "C:\Program Files\Python311\Jira-Tenable\Lib\site-packages\click\core.py", line 1130, in __call__
22:48:20     return self.main(*args, **kwargs)
22:48:20            ^^^^^^^^^^^^^^^^^^^^^^^^^^
22:48:20   File "C:\Program Files\Python311\Jira-Tenable\Lib\site-packages\click\core.py", line 1055, in main
22:48:20     rv = self.invoke(ctx)
22:48:20          ^^^^^^^^^^^^^^^^
22:48:20   File "C:\Program Files\Python311\Jira-Tenable\Lib\site-packages\click\core.py", line 1404, in invoke
22:48:20     return ctx.invoke(self.callback, **ctx.params)
22:48:20            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:48:20   File "C:\Program Files\Python311\Jira-Tenable\Lib\site-packages\click\core.py", line 760, in invoke
22:48:20     return __callback(*args, **kwargs)
22:48:20            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:48:20   File "C:\Program Files\Python311\Jira-Tenable\Lib\site-packages\tenable_jira\cli.py", line 219, in cli
22:48:20     if config.get('service', {}).get('interval', 0) > 0:
22:48:20        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:48:20 TypeError: '>' not supported between instances of 'NoneType' and 'int'`

It does seem to relate to an operator not being supported on types within cli.py ?

**Comment by spatelte** [comment]
@samryanturner It's seems like something is wrong with in [config.yaml#L41](https://github.com/tenable/integration-jira-cloud/blob/master/example_config_file.yaml#L41), Please check the value of invervel in 'service' key that should be number. 
Error is showing current value of interval is 'None' in config.ysml
