### ISSUE TITLE
Do you have an example for setting up the environment variables ?

### ISSUE THREAD

**Issue by MichaelTay0** [tenable/integration-jira-cloud#44]
Right now I have the integration running as an apple script alert that triggers every day at a certain time. ... eventually looking to move this into an AWS Lambda. 

I know that this can be triggered to run on a set cadence via
SINCE               The observed-since option.
RUN_EVERY           The run-every option.

Do you have any examples of this? What is the format that the variables should be stored in? 

For example, I want to run every day to pull results from the previous day

**Comment by SteveMcGrath** [comment]
with something like a lambda, you'd likely want to run it without the RUN_EVERY param, as it would be better suited for a docker service at that point.

instead of passing SINCE, you could use it similarly to how it's used in the examples, allowing it to be calculated at runtime.

as for the format, SINCE == unix timestamp (integer), and RUN_EVERY is hours to wait between runs (integer).
