### ISSUE TITLE
Support Accepted Risks in Tenable.io

### ISSUE THREAD

**Issue by tjgreen41** [tenable/integration-jira-cloud#8]
Is it possible to exclude vulnerabilities that have risks accepted or ignored? I see that they populate tickets.

**Comment by SteveMcGrath** [comment]
Definitely possible, would require some additional logic checking however.

**Comment by SteveMcGrath** [comment]
As Tenable.sc natively handles this in the query, I have reworded this one to better fit the use case to support.

**Comment by SteveMcGrath** [comment]
as of [v1.1.5](https://github.com/tenable/integration-jira-cloud/releases/tag/1.1.5) you can now ignore accepted risks by adding in the following configuration option:

```yaml
tenable:
    tio_ignore_accepted: true
```

**Comment by SteveMcGrath** [comment]
Added support for an additional optional parameter.

```yaml
tenable:
    tio_ignore_accepted: true
    tio_autoclose_accepted: true
```

If the autoclose param is set to true, then it will run _process_closed_vuln instead of ignoring.  Note that this is untested, and may not work as intended.  As I do not have an environment with accepted risks to test against at the moment, I am not comfortable marking this as stable quite yet.
